# Base image for Solidity development
FROM node:16

# Install Solidity compiler
RUN npm install -g solc

# Install Remix IDE
RUN npm install -g remixd

# Set up work directory
WORKDIR /workspace

CMD ["sleep", "infinity"]
